TARGET := aidemo
APPROOT ?= ./un_exist_path
TOOLPATH ?= ./un_exist_path
CFLAGS += -I$(PWD)/../Include/DhopAI
CFLAGS += -I$(PWD)/../Include/DhopSdk/Event
CFLAGS += -I App/Src/$(plat)
CFLAGS += -litop_ai

all:clean
	$(CROSS)g++ $(wildcard App/Src/*.c) $(wildcard App/Src/*.cpp)  $(CFLAGS) -o $(TARGET)

	mkdir -p $(APPROOT)/model
	@cp ./App/model/$(plat)_nnie.nnx $(APPROOT)/model

	mkdir -p $(APPROOT)/lib
	@cp $(PWD)/../Libs/libitop_ai.so $(APPROOT)/lib
	@cp $(PWD)/../Libs/libcurl.so.4 $(APPROOT)/lib
	@cp $(PWD)/../Libs/librabbitmq.so.4 $(APPROOT)/lib
	@cp $(PWD)/../Libs/libmp4v2.so.2 $(APPROOT)/lib

	mkdir -p $(APPROOT)/voice
	@cp ./App/Src/voice/bag.pcm   $(APPROOT)/voice
	@cp ./App/Src/voice/person.pcm   $(APPROOT)/voice
	@cp ./App/Src/voice/over.pcm   $(APPROOT)/voice
	@cp ./App/Src/voice/rub.pcm   $(APPROOT)/voice

	@cp $(TARGET) 	$(APPROOT)
	@cp ./App/*.lic 	$(APPROOT)
	@cp ./App/Src/alarm.ini   $(APPROOT)
	@cp ./App/Src/start.sh   $(APPROOT)


	mkdir -p $(APPROOT)/web
	@cp ./App/web/* $(APPROOT)/web -r

	@cp ./App/json/$(plat)/sample.json $(TOOLPATH)
	@cd $(TOOLPATH)/; ./ezyBuilder build sample.json
clean:
	@rm -f ./$(TARGET)
	@rm -rf $(APPROOT)/*
	@rm -rf $(TOOLPATH)/*.json	
.PHONY:
	clean
